### ISSUE TITLE
Please make sure you link to the webpage from the repo

### ISSUE THREAD

**Issue by sofer** [bo-bok/bo-bok.github.io#1]
https://github.com/bo-bok/bo-bok.github.io -> https://bo-bok.github.io/, so that we can easily view both of them. Thanks.

**Comment by jessicasalmon** [comment]
Hey @sofer, good idea. I've added https://bo-bok.github.io/ to the top of the repo page. If this isn't correct please let me know, thanks!

**Comment by sofer** [comment]
Perfect.
